version: '3'

services:
  newapp: 
    build: .
    ports: 
       - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:8003/postgres
    depends_on:
     - db
  db:
    container_name: db
    image: postgres
    ports:
      - "8003:5432"
    environment:
      - POSTGRES_PASSWORD=password
     
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}